export const routes = {
  HOME: "/",
  DATASET: "/dataset",
  DATASET_DETAIL: '/dataset/detail',
  SUPPORT: "/support",
  SUPPORT_QUESTIONS: '/support/questions',
  SUPPORT_QUESTIONS_DETAIL: '/support/questions/detail',
  ABOUTUS: "/about-us",
  APPLICATIONS: "/applications",
  AUTHENTICATION: "/authentication",
  LOGIN: `/login`,
  REGISTER: `/register`,
  RECOVER: `/recover-password`,
  RESET: `/reset-password`,
  SUCCESS_STOIRES: '/success-stories',
  SUCCESS_STOIRES_DETAIL: '/success-stories/detail',
  CHANGE: `/change-password`,
  OTP: `/otp-verification`,
  POLICY: `/privacy-policy`,
  CONTACT: `/contact-us`,
  REAL_TIME_APIS: `/real-time-apis`,
  REPORTS: '/reports',
  REPORTS_INSIGHTS: '/reports/insights',
  REPORTS_PUBLISHERS: '/reports/publisher',
  REPORTS_DATASETS: '/reports/dataset',
};
