export const routes = {
  HOME: "/",
  DATASET: "/dataset",
  DATASET_DETAIL: '/dataset/detail',
  SUPPORT: "/support",
  SUPPORT_QUESTIONS: '/support/questions',
  SUPPORT_QUESTIONS_DETAIL: '/support/questions/detail',
  ABOUTUS: "/about-us",
  APPLICATIONS: "/applications",
  AUTHENTICATION: "/authentication",
  LOGIN: `/login`,
  REGISTER: `/register`,
  RECOVER: `/recover-password`,
  RESET: `/reset-password`,
};
